### ISSUE TITLE
Can you please add License file for this project?

### ISSUE THREAD

**Issue by gssumesh** [serverless-cqrs/serverless-cqrs#1]
First of all I loved the documentation and it is something I was looking forward to in node js. I really think this project has wings. Unfortunately most of the projects within serverless-cqrs doesn't have license file. It would really help us in adoption. Thanks!

**Comment by yonahforst** [comment]
Hi there! I plan to reorganize this soon into a monorepo, I'll add the MIT license then :) Thanks for the reminder. I'd love to hear more about how you plan to use it. You can chat with me here, on the slack channel: https://serverless-cqrs-slackin.herokuapp.com/

**Comment by yonahforst** [comment]
Added and published! thanks again for the reminder :)
